name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:     
jobs:
  build:
    name: Build ipa and deb
    runs-on: macos-10.15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: brew install dpkg ldid
      - name: Build using cmake
        run: make all
      - uses: actions/upload-artifact@v2
        with:
          name: ppsspp-binaries
          path: |
            *.ipa
            *.deb
